# app.yaml

# The version of the application spec. This is the "contract" that the
# platform guarantees it will honor.
apiVersion: v1

# --- Metadata ---
# High-level information about the application.
name: super-service
tribe: platform
team: infrastructure
type: web-application
public: true
size: medium

# --- Dependencies ---
# A declarative list of external resources this application needs.
# The platform is responsible for provisioning and configuring these.
dependencies:
  database:
    type: postgres
    size: small
